[package]
name = "rusty-bruhbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15"
serde = "1.0"
async-recursion = "1.0"
once_cell = "1.17"
tracing = "0.1"
tracing-subscriber = "0.3"

serenity = { version = "0.11", features = ["client", "standard_framework", "voice", "rustls_backend"] }
songbird = { version = "0.3", features = ["yt-dlp"]}
tokio = { version = "1.25", features = ["macros", "rt-multi-thread", "signal"] }
reqwest = { version = "0.11", features = ["rustls-tls", "json"] }
