[package]
name = "rusty-bruhbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "voice", "cache"] }
songbird = { version = "0", features = ["yt-dlp"]}
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
dotenvy = "0"
reqwest = { version = "0", features = ["rustls-tls", "json"] }
serde = "1"
async-recursion = "1"
once_cell = "1"
log = "0"
simple_logger = "4"
